name: Deploy Spring Boot to EC2

on:
  workflow_dispatch:
  push:
    branches:
      - feat/github-actions

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/SpringBoot-KnowledgeBase
            git pull origin feat/sqs-events
            ./mvnw clean package -DskipTests
            sudo systemctl restart knowledgebase
            sleep 40
            curl -f http://localhost:8080/actuator/health
